module.exports=(sequelize,DataTypes)=>
sequelize.define('car',{
    id:{
        type:DataTypes.INTEGER(11),
        primaryKey:true,
        autoIncrement:true
    },
    userID:{
        type:DataTypes.STRING,
        validate:{
            //父级ID正则验证
            isInt:{
              isNumeric:true,
              msg:"{code:0,msg:'用户ID必须是数字'}"
            }
          }
    },
    goodsNum:{
        type:DataTypes.STRING,
        validate:{
            //父级ID正则验证
            isInt:{
              isNumeric:true,
              msg:"{code:0,msg:'商品数量必须是数字'}"
            }
          }
    },
    goodsID:{
        type:DataTypes.STRING,
        validate:{
            //父级ID正则验证
            isInt:{
              isNumeric:true,
              msg:"{code:0,msg:'商品ID必须是数字'}"
            }
          }
    },
    goods_ID:{//商品规格ID
        type:DataTypes.STRING,
        validate:{
            //父级ID正则验证
            isInt:{
              isNumeric:true,
              msg:"{code:0,msg:'商品规格ID必须是数字'}"
            }
          }
    },
})